### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by JacksonMaxfield** [sebi06/czitools#2]
Congrats on releasing!

Question... The license on this package is BSD but pylibcziRW and aicspylibczi are GPL. I assume license should be updated unless I just don't understand license stuff.

**Comment by sebi06** [comment]
Hi @JacksonMaxfield ,

of course you are right. That one slipped through and is corrected for v0.0.5. Thx for pointing this out. To be honest, this whole licensing stuff is still very hard for me ...

**Comment by sebi06** [comment]
Hi @JacksonMaxfield 

If aicsimagio (BSD) is using aicspylibczi (GPL) - isn' that the same problem?

**Comment by JacksonMaxfield** [comment]
We do not have an install option for czi anymore. Instead we call it out in README:

> Due to the GPL license, CZI support is not included with the [all] extra, and must be installed manually with pip install aicsimageio aicspylibczi>=3.0.5

The idea here is to say: "if you want the GPL dependency you need to explicitly manage it."

**Comment by sebi06** [comment]
Thx for the info. Of course this is not very "user-friendly" but makes sense. Unfortunately our management is not ready yet to publish pylibCZIrw under are more permissive license ...
And believe me - I really tried to comvince them

**Comment by sebi06** [comment]
BTW, is this handled for Leice, Nikon and Olympus files the same way inside aicsimageio?

**Comment by JacksonMaxfield** [comment]
Yes. The only file formats that are not "extra installable" are open formats. OME TIFF, Zarr, ND2, etc.

LIF, CZI, and any bioformats read files are all separate installs

**Comment by sebi06** [comment]
Ok. Thx for the info. I wll continue the discussion about this on aicspylibczi
