### ISSUE TITLE
czitools with Minimum Requirements

### ISSUE THREAD

**Issue by MosGeo** [sebi06/czitools#57]
I think it would be a good idea the ability to install czitools with minimum requirements. My use case is the use of czitools for reading czi files so it is pretty basic but the installation of czitools bring so much with it from plotting, graphing, other reading libraries (aicsimageio[all] which brings even more stuff such as bfio).

## Proposal
Have the ability to do something like this:
`pip install czitools[min]`
`pip install czitools[all]`

## Additional context
It looks like the library already thinking of this. For example `napari` is not in the requirements but it is being used. I just want to go further than that and say that I only want stuff for reading using pylibczirw and metadata (no plotting, no aicsimageio).

p.s. I am liking this so far. I've learned a few things reading the code. I think I can contribute here and there. I will need to do some tests first.

**Comment by sebi06** [comment]
I just released version 0.7.0 that allows to install:

`pip install czitools[all]` or

`pip install czitools`

Happy to get feedback

**Comment by sebi06** [comment]
Closed with release: https://github.com/sebi06/czitools/releases/tag/v0.7.0
