### ISSUE TITLE
Wrong index order in save_with_ZSTD_compression.ipynb

### ISSUE THREAD

**Issue by zindy** [sebi06/czitools#62]
Hey @sebi06 

I was going through your [ZSTD compression notebook](https://github.com/sebi06/czitools/blob/main/demo/notebooks/save_with_ZSTD_compression.ipynb) and noticed that the two images saved with `pyczi.create_czi()` don't look right because Z and C are reversed in your code.

This should do it (in both places where you save an image):

```
# write the same CZI image back to disk but this time with using ZSTD compression

# create a CZI to write to
print(f"Saving: {filepath_comp1}")

with pyczi.create_czi(filepath_comp1, exist_ok=True) as czidoc_w:

    # iterate over all 2D planes (index order is BTCZYX)
    for s, t, c, z in product(range(array6d.shape[0]),
                              range(array6d.shape[1]),
                              range(array6d.shape[2]),
                              range(array6d.shape[3])):

        # writing the image with compression
        czidoc_w.write(data=array6d[s, t, c, z, ...],
                       plane={"C": c, "T": t, "Z": z},
                       scene=s,
                       compression_options=cmp1,  # valid for individual planes
                       )
```

And the first index in the loop is a block, not a scene, but that's not a problem here.

For reference, `mdata.aics_dim_order` is:
```
{'R': -1,
 'I': -1,
 'M': -1,
 'H': -1,
 'V': -1,
 'B': 0,
 'S': -1,
 'T': 1,
 'C': 2,
 'Z': 3,
 'Y': 4,
 'X': 5,
 'A': -1}
```

(no scene index)

Kind regards,
Egor

**Comment by sebi06** [comment]
Hi @zindy 

thanks for pointing this out. I fixed it and merged it to the main. Maybe I will do  release soon.
